apiVersion: v1
kind: Template
labels:
  template: nginx
metadata:
  annotations:
    description: |
      Template to deploy static content with Nginx.
      Documentation available at https://git.global.paas.gsnetcloud.corp/images/nginx.
      Contact support by email global_paas@produban.com or JIRA Global-PaaS Support
    iconClass: icon-load-balancer
    tags: instant-app,webapp,nginx,binary deployment,statics
    openshift.io/provider-display-name: Cloud Competence Service.
  name: nginx
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: nginx
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: nginx
    name: ${APP_NAME}-status
  spec:
    ports:
    - name: 8081-tcp
      nodePort: 0
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: nginx
    name: ${APP_NAME}
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: nginx
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app_name: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
          template: nginx
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: ARTIFACT_URL
            value: ${ARTIFACT_URL}
          - name: ARTIFACTCONF_URL
            value: ${ARTIFACTCONF_URL}
          - name: PROJECT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: ${TZ}
          image: {TAGGED_IMAGE}
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/metadata
            name: podinfo
            readOnly: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - metadata:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
          name: podinfo
  status: {}
parameters:
- description: Application name
  displayName: Application name
  name: APP_NAME
  required: true
- description: Artifact url (tgz, tar.gz, git repository)
  displayName: Artifact url
  name: ARTIFACT_URL
- description: Artifactconf url (tgz, tar.gz)
  displayName: Artifactconf url
  name: ARTIFACTCONF_URL
- description: TimeZone for the running containers.
  displayName: TimeZone
  name: TZ
  value: Europe/Madrid
